- name: install tools (apt)
  become: yes
  apt:
    pkg:
      - silversearcher-ag
      - tree

- name: clone fzf repo
  git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf
  notify:
    - install fzf

- name: get dry installer
  become: yes
  get_url:
    url: https://moncho.github.io/dry/dryup.sh
    dest: /tmp/dryup.sh
    mode: 0740
  notify:
    - "dry setup"

- name: install pipx
  become: yes
  pip:
    name: pipx

- name: install utils with pipx
  shell: pipx install {{ item }}
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.local/pipx/venvs/{{ item }}"
  loop:
    - httpie
    - ansible
    - pipenv

- name: inject docker-compose into ansible venv
  shell: pipx inject ansible docker-compose
  args:
    executable: /bin/bash
