- name: download bash-powerline
  get_url:
    url: https://raw.githubusercontent.com/ronaldotd/bash-powerline/master/bash-powerline.sh
    dest: ~/.bash_powerline.sh

- name: add bash-powerline to bashrc
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK - bash-powerline"
    block: source .bash_powerline.sh
