- name: create package manager start dir
  file:
    path: ~/.vim/pack/plugins/start
    state: directory

- name: create package manager opt dir
  file:
    path: ~/.vim/pack/plugins/opt
    state: directory

- name: copy .vimrc
  copy:
    src: .vimrc
    dest: ~/.vimrc

- name: install vim plugins
  git:
    repo: "{{ item.repo }}"
    dest: ~/.vim/pack/plugins/start/{{ item.name }}
  loop:
    - { name: "fzf", repo: "https://github.com/junegunn/fzf" }
    - { name: "fzf.vim", repo: "https://github.com/junegunn/fzf.vim" }
    - { name: "jedi-vim", repo: "https://github.com/davidhalter/jedi-vim" }
    - { name: "nerdtree", repo: "https://github.com/scrooloose/nerdtree" }
    - { name: "papercolor-theme", repo: "https://github.com/NLKNguyen/papercolor-theme" }
    - { name: "vim-airline", repo: "https://github.com/vim-airline/vim-airline" }
    - { name: "vim-flake8", repo: "https://github.com/nvie/vim-flake8" }
    - { name: "vim-fugitive", repo: "https://github.com/tpope/vim-fugitive" }
    - { name: "vim-gitgutter", repo: "https://github.com/airblade/vim-gitgutter"}
