  - name: update all packages
    become: yes
    apt:
      update_cache: yes
      upgrade: dist

  - name: install base packages
    become: yes
    apt:
      pkg:
        - "{{ item }}"
    loop:
      - python3-pip
      - python3-venv

  - name: update pip
    become: yes
    pip:
      name: pip
      state: latest
      executable: pip3

  - name: create user
    become: yes
    user:
      name: "{{ os_user }}"
      password: "{{ os_pass | password_hash('sha512') }}"
      update_password: on_create
      groups: sudo, docker
      shell: /bin/bash

  - name: copy authorized keys
    become: yes
    authorized_key:
      user: "{{ os_user }}"
      key: "{{ authorized_keys_url }}"
    when: authorized_keys_url|length > 0

  - name: create ssh keys dir
    become: yes
    become_user: "{{ os_user }}"
    file:
      path: ~/.ssh
      state: directory

  - name: copy ssh keys
    become: yes
    become_user: "{{ os_user }}"
    copy:
      src: ~/.ssh/{{ item }}
      dest: ~/.ssh/{{ item }}
      mode: 0600
    loop:
      - id_rsa
      - id_rsa.pub

  - name: set timezone
    become: yes
    timezone:
      name: America/Sao_Paulo

  - name: create sudo_as_admin_successful file
    become: yes
    become_user: "{{ os_user }}"
    copy:
      content: ""
      dest: ~/.sudo_as_admin_successful
      force: no
