  - name: update all packages
    become: yes
    apt:
      update_cache: yes
      upgrade: dist

  - name: install base packages
    become: yes
    apt:
      pkg:
        - "{{ item }}"
    loop:
      - python3-pip
      - python3-venv

  - name: update pip
    become: yes
    pip:
      name: pip
      state: latest
      executable: pip3

  - name: install docker-compose
    pip:
      name: docker-compose

  - name: create ssh keys dir
    file:
      path: ~/.ssh
      state: directory

  - name: copy ssh keys
    copy:
      src: ~/.ssh/{{ item }}
      dest: ~/.ssh/{{ item }}
      mode: 0600
    loop:
      - id_rsa
      - id_rsa.pub

  - name: set timezone
    become: yes
    timezone:
      name: America/Sao_Paulo

  - name: create sudo_as_admin_successful file
    copy:
      content: ""
      dest: ~/.sudo_as_admin_successful
      force: no
