- name: Provision dev machine
  hosts: all
  vars_files:
    - vars.yaml
  tasks:
    - name: provision base resources
      include_role:
        name: base

    - name: provision additional resourcess
      include_role:
        name: "{{ role.key }}"
      when: role.value.include
      loop: "{{ lookup('dict', provision_roles) }}"
      loop_control:
        loop_var: role
